-- 为ORDER_DELIVERY_INFO表添加配送地址、配送距离和配送费用字段
ALTER TABLE ORDER_DELIVERY_INFO ADD DELIVERY_ADDRESS VARCHAR2(255);
ALTER TABLE ORDER_DELIVERY_INFO ADD DELIVERY_LATITUDE NUMBER(20, 6);
ALTER TABLE ORDER_DELIVERY_INFO ADD DELIVERY_LONGITUDE NUMBER(20, 6);
ALTER TABLE ORDER_DELIVERY_INFO ADD DELIVERY_DISTANCE NUMBER(10, 2);
ALTER TABLE ORDER_DELIVERY_INFO ADD DELIVERY_FEE NUMBER(10, 2);

-- 添加字段注释
COMMENT ON COLUMN ORDER_DELIVERY_INFO.DELIVERY_ADDRESS IS '配送地址';
COMMENT ON COLUMN ORDER_DELIVERY_INFO.DELIVERY_LATITUDE IS '配送地址纬度';
COMMENT ON COLUMN ORDER_DELIVERY_INFO.DELIVERY_LONGITUDE IS '配送地址经度';
COMMENT ON COLUMN ORDER_DELIVERY_INFO.DELIVERY_DISTANCE IS '配送距离(公里)';
COMMENT ON COLUMN ORDER_DELIVERY_INFO.DELIVERY_FEE IS '配送费用';