-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgv60fTZ9nlGcNQS/e
uZKZwA0pus/b0jcK1kcwkx9v/Z6gCgYIKoZIzj0DAQehRANCAASnjIL1qOWBwwat
XfjiHmsV3LXEjpVfRt3b1FQiMHJd+Mw3tsKWbdYnAMvuSlea/myjaJx8AAlVhPDy
ha9dB4GS
-----END PRIVATE KEY-----