-- 为配送信息表添加城市字段
-- 版本：V1.0.2
-- 执行时间：2025-01-XX
-- 说明：为ORDER_DELIVERY_INFO表添加city字段，用于存储配送城市信息

-- 添加城市字段
ALTER TABLE ORDER_DELIVERY_INFO ADD CITY VARCHAR2(100);

-- 添加字段注释
COMMENT ON COLUMN ORDER_DELIVERY_INFO.CITY IS '城市';

-- 创建索引（可选，如果经常按城市查询）
-- CREATE INDEX IDX_ORDER_DELIVERY_INFO_CITY ON ORDER_DELIVERY_INFO(CITY);

-- 验证字段是否添加成功
-- SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, COMMENTS 
-- FROM USER_TAB_COLUMNS 
-- WHERE TABLE_NAME = 'ORDER_DELIVERY_INFO' 
-- AND COLUMN_NAME = 'CITY';
