-- 为配送信息表添加配送国家、配送城市、配送邮编字段
-- 版本：V1.0.3
-- 执行时间：2025-01-XX
-- 说明：为ORDER_DELIVERY_INFO表添加配送国家、配送城市、配送邮编字段，并将原city字段重命名为delivery_city

-- 添加配送国家字段
ALTER TABLE ORDER_DELIVERY_INFO ADD DELIVERY_COUNTRY VARCHAR2(100);

-- 添加配送城市字段
ALTER TABLE ORDER_DELIVERY_INFO ADD DELIVERY_CITY VARCHAR2(100);

-- 添加配送邮编字段
ALTER TABLE ORDER_DELIVERY_INFO ADD DELIVERY_POSTAL_CODE VARCHAR2(20);

-- 将原city字段数据迁移到delivery_city字段
UPDATE ORDER_DELIVERY_INFO SET DELIVERY_CITY = CITY WHERE CITY IS NOT NULL;

-- 删除原city字段
ALTER TABLE ORDER_DELIVERY_INFO DROP COLUMN CITY;

-- 添加字段注释
COMMENT ON COLUMN ORDER_DELIVERY_INFO.DELIVERY_COUNTRY IS '配送国家';
COMMENT ON COLUMN ORDER_DELIVERY_INFO.DELIVERY_CITY IS '配送城市';
COMMENT ON COLUMN ORDER_DELIVERY_INFO.DELIVERY_POSTAL_CODE IS '配送邮编';

-- 创建索引（可选，如果经常按配送城市查询）
-- CREATE INDEX IDX_ORDER_DELIVERY_INFO_DELIVERY_CITY ON ORDER_DELIVERY_INFO(DELIVERY_CITY);

-- 验证字段是否添加成功
-- SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, COMMENTS 
-- FROM USER_TAB_COLUMNS 
-- WHERE TABLE_NAME = 'ORDER_DELIVERY_INFO' 
-- AND COLUMN_NAME IN ('DELIVERY_COUNTRY', 'DELIVERY_CITY', 'DELIVERY_POSTAL_CODE');
