-- 如果表存在则删除
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCT_INVENTORY_RESERVATION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE PRODUCT_INVENTORY_RESERVATION (
    ID VARCHAR2(32) NOT NULL PRIMARY KEY,
    ORDER_ID VARCHAR2(32) NOT NULL,
    PRODUCT_ID VARCHAR2(30) NOT NULL,
    TENANT_ID VARCHAR2(32) NOT NULL,
    RESERVED_QUANTITY NUMBER(8)  DEFAULT 0 NOT NULL,
    DEDUCTED_QUANTITY NUMBER(8) DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(16) DEFAULT 'RESERVED' NOT NULL,
    CREATE_TIME NUMBER(20) DEFAULT 0 NOT NULL,
    UPDATE_TIME NUMBER(20),
    VERSION NUMBER(8) DEFAULT 1 NOT NULL,
    DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

COMMENT ON TABLE PRODUCT_INVENTORY_RESERVATION IS '商品库存占用表';
COMMENT ON COLUMN PRODUCT_INVENTORY_RESERVATION.ID IS '主键（雪花ID）';
COMMENT ON COLUMN PRODUCT_INVENTORY_RESERVATION.ORDER_ID IS '订单ID';
COMMENT ON COLUMN PRODUCT_INVENTORY_RESERVATION.PRODUCT_ID IS '商品ID';
COMMENT ON COLUMN PRODUCT_INVENTORY_RESERVATION.TENANT_ID IS '租户ID';
COMMENT ON COLUMN PRODUCT_INVENTORY_RESERVATION.RESERVED_QUANTITY IS '预留数量';
COMMENT ON COLUMN PRODUCT_INVENTORY_RESERVATION.DEDUCTED_QUANTITY IS '已扣减数量';
COMMENT ON COLUMN PRODUCT_INVENTORY_RESERVATION.STATUS IS '状态：RESERVED-预留，DEDUCTED-已扣减，RELEASED-已释放';
COMMENT ON COLUMN PRODUCT_INVENTORY_RESERVATION.CREATE_TIME IS '创建时间（毫秒时间戳）';
COMMENT ON COLUMN PRODUCT_INVENTORY_RESERVATION.UPDATE_TIME IS '更新时间（毫秒时间戳）';
COMMENT ON COLUMN PRODUCT_INVENTORY_RESERVATION.VERSION IS '版本号';
COMMENT ON COLUMN PRODUCT_INVENTORY_RESERVATION.DELETED IS '删除标记';

-- 索引
CREATE INDEX IDX_PIR_ORDER_ID ON PRODUCT_INVENTORY_RESERVATION (ORDER_ID);
CREATE INDEX IDX_PIR_PRODUCT_TENANT ON PRODUCT_INVENTORY_RESERVATION (PRODUCT_ID, TENANT_ID);
CREATE INDEX IDX_PIR_STATUS ON PRODUCT_INVENTORY_RESERVATION (STATUS, DELETED);
