-- 商户
delete  from MERCHANT_ADVERTISED where  DELETED is not null;

delete  from MERCHANT_BANNER where  DELETED is not null;

delete  from MERCHANT_DISTRIBUTION where  DELETED is not null;

delete  from MERCHANT_FILE_UPLOAD where  DELETED is not null;

delete  from MERCHANT_FREIGHT where  DELETED is not null;

delete  from MERCHANT_HOLIDAY where  DELETED is not null;

delete  from MERCHANT_INFO where  DELETED is not null;

delete  from MERCHANT_KEY_WORDS where  DELETED is not null;

delete  from MERCHANT_MARKING where  DELETED is not null;

delete  from MERCHANT_OPENING_HOURS where  DELETED is not null;

delete  from MERCHANT_SIDE_BAR where  DELETED is not null;

delete  from MERCHANT_SPECIFICATION where  DELETED is not null;

delete  from MERCHANT_SUB_SPECIFICATION where  DELETED is not null;

delete  from MERCHANT_SUBSCRIBE where  DELETED is not null;

delete  from MERCHANT_WAREHOUSE where  DELETED is not null;

delete  from MERCHANT_WAREHOUSE where  DELETED is not null;

delete  from MERCHANT_WAREHOUSE_SEAT where  DELETED is not null;

-- 商品
delete  from PRODUCT_AUCTION where  DELETED is not null;

delete  from PRODUCT_AUCTION_PRICE_LOG where  DELETED is not null;

delete  from PRODUCT_BASE_INFO where  DELETED is not null;

delete  from PRODUCT_KEYWORDS where  DELETED is not null;

delete  from PRODUCT_LIST where  DELETED is not null;

delete  from PRODUCT_MARKING where  DELETED is not null;

delete  from PRODUCT_PREFERENTIAL where  DELETED is not null;

delete  from PRODUCT_SPECIFICATION where  DELETED is not null;

delete  from PRODUCT_SUB_SPECIFICATION where  DELETED is not null;

delete  from PRODUCT_TYPE where  DELETED is not null;

delete  from PRODUCT_WHOLESALE where  DELETED is not null;


-- 清理用户
delete from USERS where identity != 4;

-- 骑手
TRUNCATE TABLE  RIDER RESTART IDENTITY CASCADE;

-- 地址
TRUNCATE TABLE  USER_ADDRESS RESTART IDENTITY CASCADE;

-- 站内消息
TRUNCATE TABLE  WS_NOTIFICATION_MESSAGE RESTART IDENTITY CASCADE;

-- 订单
TRUNCATE TABLE  ORDERS RESTART IDENTITY CASCADE;

TRUNCATE TABLE  ORDER_ITEMS RESTART IDENTITY CASCADE;

TRUNCATE TABLE  ORDER_DELIVERY_INFO RESTART IDENTITY CASCADE;

TRUNCATE TABLE  ORDER_OPERATION_LOGS RESTART IDENTITY CASCADE;

TRUNCATE TABLE  ORDER_PAYMENTS RESTART IDENTITY CASCADE;

TRUNCATE TABLE  ORDER_STATUS_LOGS RESTART IDENTITY CASCADE;

TRUNCATE TABLE  ORDER_ITEM_SPECIFICATIONS RESTART IDENTITY CASCADE;

TRUNCATE TABLE  ORDER_RESERVATION_INFO RESTART IDENTITY CASCADE;

-- 会员中心
TRUNCATE TABLE  MERCHANTS RESTART IDENTITY CASCADE;

TRUNCATE TABLE  ACCOUNTS RESTART IDENTITY CASCADE;

TRUNCATE TABLE  PAYMENT_ACCOUNT_FLOW RESTART IDENTITY CASCADE;

TRUNCATE TABLE  FEE_CONFIG RESTART IDENTITY CASCADE;

TRUNCATE TABLE  PAYMENT_ORDER RESTART IDENTITY CASCADE;

TRUNCATE TABLE  PAYMENT_TRANSACTIONS RESTART IDENTITY CASCADE;

TRUNCATE TABLE  WALLETS RESTART IDENTITY CASCADE;

-- 发票
TRUNCATE TABLE  PAY_INVOICE RESTART IDENTITY CASCADE;

TRUNCATE TABLE  PAY_INVOICE_ITEM RESTART IDENTITY CASCADE;

TRUNCATE TABLE  T_PARTY RESTART IDENTITY CASCADE;

TRUNCATE TABLE  PAY_ITEM RESTART IDENTITY CASCADE;

